cmake_minimum_required(VERSION 3.20)

project(dynamic_programming)
set(CMAKE_CXX_STANDARD 17)

add_executable(coin_change coin_change.cpp)
add_executable(fibonacci fibonacci.cpp)
add_executable(lcs lcs.cpp)
add_executable(knapsack knapsack.cpp)
add_executable(climbing_stairs climbing_stairs.cpp)
add_executable(house_rob house_rob.cpp)
add_executable(fibonacci_tabulation fibonacci_tabulation.cpp)
